<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Susan Eileen Fox">
<meta name="dcterms.date" content="2025-10-20">

<title>Homework 3 – Vision Readings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-226bd0f977fa82dfae4534cac220d79a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9011e249e8d359b0658fa71d60c1fa6f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Vision Readings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Homework 3</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Susan Eileen Fox </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 20, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#question-1-implementing-the-bubblemix-function" id="toc-question-1-implementing-the-bubblemix-function" class="nav-link" data-scroll-target="#question-1-implementing-the-bubblemix-function">Question 1: Implementing the <code>bubbleMix</code> function</a>
  <ul class="collapse">
  <li><a href="#combining-part-of-an-image-with-another" id="toc-combining-part-of-an-image-with-another" class="nav-link" data-scroll-target="#combining-part-of-an-image-with-another">Combining part of an image with another</a></li>
  <li><a href="#cropping-to-a-maximal-width-and-height" id="toc-cropping-to-a-maximal-width-and-height" class="nav-link" data-scroll-target="#cropping-to-a-maximal-width-and-height">Cropping to a maximal width and height</a></li>
  <li><a href="#making-a-mask-with-circles-on-it" id="toc-making-a-mask-with-circles-on-it" class="nav-link" data-scroll-target="#making-a-mask-with-circles-on-it">Making a mask with circles on it</a></li>
  <li><a href="#making-the-negative-mask" id="toc-making-the-negative-mask" class="nav-link" data-scroll-target="#making-the-negative-mask">Making the negative mask</a></li>
  <li><a href="#applying-the-masks-to-the-images" id="toc-applying-the-masks-to-the-images" class="nav-link" data-scroll-target="#applying-the-masks-to-the-images">Applying the masks to the images</a></li>
  <li><a href="#add-the-two-images-together" id="toc-add-the-two-images-together" class="nav-link" data-scroll-target="#add-the-two-images-together">Add the two images together</a></li>
  <li><a href="#specifications-for-question-1" id="toc-specifications-for-question-1" class="nav-link" data-scroll-target="#specifications-for-question-1">Specifications for Question 1</a></li>
  </ul></li>
  <li><a href="#question-2-annotating-a-complex-program" id="toc-question-2-annotating-a-complex-program" class="nav-link" data-scroll-target="#question-2-annotating-a-complex-program">Question 2: Annotating a complex program</a>
  <ul class="collapse">
  <li><a href="#specifications-for-question-2" id="toc-specifications-for-question-2" class="nav-link" data-scroll-target="#specifications-for-question-2">Specifications for Question 2</a></li>
  </ul></li>
  <li><a href="#question-3-completing-a-multi-function-program-using-pseudocode" id="toc-question-3-completing-a-multi-function-program-using-pseudocode" class="nav-link" data-scroll-target="#question-3-completing-a-multi-function-program-using-pseudocode">Question 3: Completing a multi-function program, using pseudocode</a>
  <ul class="collapse">
  <li><a href="#pseudocode-for-adjusthue" id="toc-pseudocode-for-adjusthue" class="nav-link" data-scroll-target="#pseudocode-for-adjusthue">Pseudocode for <code>adjustHue</code></a></li>
  <li><a href="#pseudocode-for-adjustsat" id="toc-pseudocode-for-adjustsat" class="nav-link" data-scroll-target="#pseudocode-for-adjustsat">Pseudocode for <code>adjustSat</code></a></li>
  <li><a href="#pseudocode-for-adjustval" id="toc-pseudocode-for-adjustval" class="nav-link" data-scroll-target="#pseudocode-for-adjustval">Pseudocode for <code>adjustVal</code></a></li>
  <li><a href="#testing-your-program" id="toc-testing-your-program" class="nav-link" data-scroll-target="#testing-your-program">Testing your program</a></li>
  <li><a href="#specifications-for-question-3" id="toc-specifications-for-question-3" class="nav-link" data-scroll-target="#specifications-for-question-3">Specifications for Question 3</a></li>
  </ul></li>
  <li><a href="#question-4-writing-pseudocode" id="toc-question-4-writing-pseudocode" class="nav-link" data-scroll-target="#question-4-writing-pseudocode">Question 4: Writing pseudocode</a>
  <ul class="collapse">
  <li><a href="#specifications-for-question-4" id="toc-specifications-for-question-4" class="nav-link" data-scroll-target="#specifications-for-question-4">Specifications for Question 4</a></li>
  </ul></li>
  <li><a href="#question-5-augmenting-an-existing-program" id="toc-question-5-augmenting-an-existing-program" class="nav-link" data-scroll-target="#question-5-augmenting-an-existing-program">Question 5: Augmenting an existing program</a>
  <ul class="collapse">
  <li><a href="#specifications-for-question-5" id="toc-specifications-for-question-5" class="nav-link" data-scroll-target="#specifications-for-question-5">Specifications for Question 5</a></li>
  </ul></li>
  <li><a href="#question-6-writing-a-program-of-your-own-design" id="toc-question-6-writing-a-program-of-your-own-design" class="nav-link" data-scroll-target="#question-6-writing-a-program-of-your-own-design">Question 6: Writing a program of your own design</a>
  <ul class="collapse">
  <li><a href="#specifications-for-question-6" id="toc-specifications-for-question-6" class="nav-link" data-scroll-target="#specifications-for-question-6">Specifications for Question 6</a></li>
  </ul></li>
  <li><a href="#what-to-hand-in" id="toc-what-to-hand-in" class="nav-link" data-scroll-target="#what-to-hand-in">What to hand in</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="overview" class="level1">
<h1>Overview</h1>
<p><strong>This assignment is individual work!</strong></p>
<ul>
<li>Do not share or borrow solutions from other students.</li>
<li>Do not use AI assistants to generate code for you.</li>
<li><strong>Do</strong> ask preceptors and instructors for help with the code, including what to write and debugging.</li>
<li><strong>Do</strong> ask peers or AI assistants for help in understanding error messages, but not for help in writing or debugging your work.</li>
</ul>
<p>This homework assignment will ask you to demonstrate your skills at understanding, debugging, planning, and creating python scripts and function. The list of topics for this assignment include:</p>
<ul>
<li>While loops</li>
<li>Connecting and processing frames of video from files or webcam</li>
<li>Image processing and transformations including:
<ul>
<li>masking and thresholding images</li>
<li>geometric transformations</li>
<li>image filtering</li>
<li>motion and color tracking</li>
</ul></li>
</ul>
<p><strong>To hand in:</strong> You will use the Homework 3 Github Assignment to set up this assignment, and to <em>push</em> your code to save it to the cloud, to hand it in. Note that all your work will go into a single file for this assignment. A starter file, <code>hw3Code.py</code> will be provided, add your work there, and test your work with the <code>hw3Checker.py</code> file.</p>
<p><strong>Handling images:</strong> I will provide in the Github assignment just those images you need to have to do this assignment.</p>
</section>
<section id="question-1-implementing-the-bubblemix-function" class="level1">
<h1>Question 1: Implementing the <code>bubbleMix</code> function</h1>
<p>For this question, you will implement a function, <code>bubbleMix</code>, that will combine two images using masks. Your function will take two images as inputs, and will do the following general steps (more details about each step below):</p>
<ul>
<li>First, you will crop the two pictures so that they are the same size, as large as is possible given the images’ dimensions</li>
<li>Next you will create a mask and its inverse: the mask will be black with 30 white random circles draw on it</li>
<li>You will use the two masks to select the parts of one image that are outside the circles, and the parts of the other image that are inside the circles</li>
<li>You will add the two images together to combine them</li>
<li>Finally, you will return the combined image</li>
</ul>
<section id="combining-part-of-an-image-with-another" class="level2">
<h2 class="anchored" data-anchor-id="combining-part-of-an-image-with-another">Combining part of an image with another</h2>
<p>Suppose we wanted to combine part of an image with another: like placing the outline of our wild columbine flower onto the Bear Lake background (the original images are shown in <a href="#fig-q1origIms" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div id="fig-q1origIms" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-q1origIms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/fgim.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="wildColumbine.jpg"><img src="HW3-Images/fgim.png" class="img-fluid figure-img"></a></p>
<figcaption><code>wildColumbine.jpg</code></figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/bearLake.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="bearLake.jpg"><img src="HW3-Images/bearLake.jpg" class="img-fluid figure-img"></a></p>
<figcaption><code>bearLake.jpg</code></figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-q1origIms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The two starting images, cropped (if needed) to the same size
</figcaption>
</figure>
</div>
<p>If the shape were rectangular, we could use slicing to redefine a portion of the background picture. But the flower is not at all rectangular! In this case, we can use masking to combine the images.</p>
<ul>
<li>We make a mask where the white pixels are exactly the parts of the foreground image we want to keep and copy to the background. The mask in <a href="#fig-q1masks" class="quarto-xref">Figure&nbsp;2</a> was made with the <code>threshold</code> function.</li>
<li>We make another mask that is the opposite of the first: black where the first was white, and white where it was black</li>
</ul>
<div id="fig-q1masks" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-q1masks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/mask1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Mask of flower made by threshold"><img src="HW3-Images/mask1.png" class="img-fluid figure-img"></a></p>
<figcaption>Mask of flower made by <code>threshold</code></figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/mask2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Mask that is the opposite of the first (255 - mask1)"><img src="HW3-Images/mask2.png" class="img-fluid figure-img"></a></p>
<figcaption>Mask that is the opposite of the first <code>(255 - mask1)</code></figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-q1masks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The two masks, one made using <code>threshold</code> and the other made as the negative of the first
</figcaption>
</figure>
</div>
<ul>
<li>Next, we apply the first mask to the wild columbine picture, and the second mask to the Bear Lake picture, producing results shown in <a href="#fig-q1Masked" class="quarto-xref">Figure&nbsp;3</a>. The two images complement each other: where one image has black pixels, the other has color, and vice versa.</li>
</ul>
<div id="fig-q1Masked" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-q1Masked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/part1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Masking of flower with first mask"><img src="HW3-Images/part1.png" class="img-fluid figure-img"></a></p>
<figcaption>Masking of flower with first mask</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/part2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Masking of background with second mask"><img src="HW3-Images/part2.png" class="img-fluid figure-img"></a></p>
<figcaption>Masking of background with second mask</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-q1Masked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The result of masking the two images with the two masks
</figcaption>
</figure>
</div>
<ul>
<li>Now, if we just add the two masked images together, we will have black (0, 0, 0) added to a color at every pixel location. So the colors never conflict!</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/Final.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Final result of adding the masked images together"><img src="HW3-Images/Final.png" class="img-fluid figure-img" alt="Final result of adding the masked images together"></a></p>
<figcaption>Final result of adding the masked images together</figcaption>
</figure>
</div>
<p><strong>You are going to implement this process in this function, with a mask made of random circles.</strong></p>
</section>
<section id="cropping-to-a-maximal-width-and-height" class="level2">
<h2 class="anchored" data-anchor-id="cropping-to-a-maximal-width-and-height">Cropping to a maximal width and height</h2>
<p>To crop two images to the same size, we are limited by the dimensions of each image. The largest possible crop will have a height that is the smaller of the two images’ heights, and a width that is the smaller of the two images’ widths.</p>
<ul>
<li>Get the dimensions of each image</li>
<li>Find the smaller width and smaller height</li>
<li>Crop each image to have that width and height (using Numpy slicing)</li>
</ul>
</section>
<section id="making-a-mask-with-circles-on-it" class="level2">
<h2 class="anchored" data-anchor-id="making-a-mask-with-circles-on-it">Making a mask with circles on it</h2>
<p>For the next step, you want to make a black image the same size and type as the cropped images (make sure it has three channels to simplify things). Then, write a loop that will draw random circles on the image:</p>
<ul>
<li>Repeat 30 times</li>
<li>Pick a random radius from a reasonable range (in my examples I used radii between 10 and 50)</li>
<li>Pick random starting positions that are in the image (circles can be cut off by the edge of the picture, but should be partially visible)</li>
<li>Draw a white circle on the black image</li>
</ul>
</section>
<section id="making-the-negative-mask" class="level2">
<h2 class="anchored" data-anchor-id="making-the-negative-mask">Making the negative mask</h2>
<p>To make a negative of the original mask, subtract the mask from 255. Where the original mask was white, we will be subtracting 255 from 255, producing 0. And where the original mask was black, we are subtracting 0 from 255, producing 255.</p>
</section>
<section id="applying-the-masks-to-the-images" class="level2">
<h2 class="anchored" data-anchor-id="applying-the-masks-to-the-images">Applying the masks to the images</h2>
<p>Use <code>cv2.bitwise_and</code> to combine the cropped version of the first image with the first mask, and then combine the cropped version of the second image with the second mask.</p>
</section>
<section id="add-the-two-images-together" class="level2">
<h2 class="anchored" data-anchor-id="add-the-two-images-together">Add the two images together</h2>
<p>The last step is to add the two images together, and to <strong>return the result!</strong></p>
<p>Below is a sample call to the function, and the final result.</p>
<div id="d6901eab" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a>img1 <span class="op">=</span> cv2.imread(<span class="st">"SampleImages/winterRobin.jpg"</span>)</span>
<span id="cb1-2"><a href="#cb1-2"></a>img2 <span class="op">=</span> cv2.imread(<span class="st">"SampleImages/selbyWinter.jpg"</span>)</span>
<span id="cb1-3"><a href="#cb1-3"></a>finalPic1 <span class="op">=</span> bubbleMix(img2, img1)</span>
<span id="cb1-4"><a href="#cb1-4"></a>cv2.imshow(<span class="st">"BubbleMix"</span>, finalPic1)</span>
<span id="cb1-5"><a href="#cb1-5"></a>cv2.waitKey()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="HW3-Images/BubbleExample.png" class="img-fluid figure-img"></p>
<figcaption>Final result of the sample call</figcaption>
</figure>
</div>
</section>
<section id="specifications-for-question-1" class="level2">
<h2 class="anchored" data-anchor-id="specifications-for-question-1">Specifications for Question 1</h2>
<p><strong>Base specifications:</strong></p>
<ul>
<li>Solution defines a function called <code>bubbleMix</code></li>
<li>Function header correctly specifies the name and inputs for this function</li>
<li>Function correctly crops both images to be the same (maximal) size</li>
<li>Function correctly constructs the first mask with random circles, and its opposite</li>
<li>Function correctly applies masks to cropped images</li>
<li>Function correctly adds the masked images together</li>
<li>Function returns the final resul</li>
</ul>
<p><strong>Extended specifications:</strong></p>
<ul>
<li>Code includes a triple-quoted <em>docstring</em> that describes the function’s input, purpose, and results</li>
<li>Student name is at the top of the file</li>
<li>Any completed TODO comments have been removed</li>
<li>File format has appropriate style:
<ul>
<li><code>import</code> statements at the top</li>
<li>then function definitions with no script elements</li>
<li>then the main script, all insidde the <code>if __name__ == '__main__':</code> statement</li>
</ul></li>
</ul>
<p><strong>Ratings:</strong></p>
<ul>
<li>To receive a gold rating, complete at least 8 specifications, at least 5 of them base</li>
<li>To receive a silver rating, complete at least 7 specifications, at least 4 of them base</li>
<li>To receive a bronze rating, complete at least 6 specifications, at least 3 of them base</li>
</ul>
</section>
</section>
<section id="question-2-annotating-a-complex-program" class="level1">
<h1>Question 2: Annotating a complex program</h1>
<p>In the <code>hw3Code.py</code> file, there is a program called <code>getBox</code>. It has four helper functions that help it to perform its purpose.</p>
<p>We’re not going to tell you what <code>getBox</code> does. Your task is to figure out what this program does, at a high level, and in the details of the code.</p>
<ul>
<li>Run the program</li>
<li>Read the code</li>
<li>Make a copy of the code and experiment with it (keep the original to come back to)</li>
</ul>
<p>Figure out how to interact with the program, what the goal of the program is, and what each section of code does.</p>
<p>Then, add annotations and descriptive docstrings as indicated in the code file.</p>
<ul>
<li>Be detailed</li>
<li>Do not just paraphrase what the lines of code say: focus on the <strong>purpose</strong> of each section of code</li>
<li>Docstrings for function calls should describe what the inputs are and any return value, as well as the purpose of the function</li>
</ul>
<section id="specifications-for-question-2" class="level2">
<h2 class="anchored" data-anchor-id="specifications-for-question-2">Specifications for Question 2</h2>
<p><strong>Base specifications:</strong></p>
<ul>
<li>Docstring for <code>getBox</code> is detailed, accurate, and formatted as a triple-quoted string positioned right below the <code>def</code> line</li>
<li>Docstring for <code>initCanvas</code> is detailed, accurate, and formatted as a triple-quoted string positioned right below the <code>def</code> line</li>
<li>Docstring for <code>onTarget</code> is detailed, accurate, and formatted as a triple-quoted string positioned right below the <code>def</code> line</li>
<li>Docstring for <code>moveTarget</code> is detailed, accurate, and formatted as a triple-quoted string positioned right below the <code>def</code> line</li>
<li>Docstring for <code>showFinal</code> is detailed, accurate, and formatted as a triple-quoted string positioned right below the <code>def</code> line</li>
<li>In the <code>getBox</code> function you have written at least 3 detailed, accurate hash-mark comments</li>
<li>In the <code>getBox</code> function, you have written at least 2 additional detailed, accurate hash-mark comments</li>
<li>In the <code>getBox</code> function, you have written at least 2 additional detailed, accurate hash-mark comments</li>
</ul>
<p><strong>Extended specifications:</strong></p>
<ul>
<li>Student name is at the top of the file</li>
<li>Any completed TODO comments have been removed</li>
<li>File format has appropriate style:
<ul>
<li><code>import</code> statements at the top</li>
<li>then function definitions with no script elements</li>
<li>then the main script, all inside the <code>if __name__ == '__main__':</code> statement</li>
</ul></li>
</ul>
<p><strong>Ratings:</strong></p>
<ul>
<li>To receive a gold rating, fully complete at least 8 specifications, at least 6 base, partially complete at least 1 more</li>
<li>To receive a silver rating, fully complete at least 7 specifications, at least 5 base, partially complete at least 1 more</li>
<li>To receive a bronze rating, fully complete at least 6 specifications, at least 4 base</li>
</ul>
</section>
</section>
<section id="question-3-completing-a-multi-function-program-using-pseudocode" class="level1">
<h1>Question 3: Completing a multi-function program, using pseudocode</h1>
<p>Under Question 3 in the <code>hw3Code.py</code> file, there is a partially-completed program. We have provided the main function, <code>findBall</code>, and a helper, <code>applyBounds</code>. You will be implementing three helper functions (all three are very similar to each other).</p>
<p>You learned about using lower and upper bounds on an HSV image with the <code>inRange</code> function, to identify the location of a colorful object in an image. You may remember that figuring out the best bounds can be very tricky.</p>
<p>The purpose of this program is to help the user to select the right hue, saturation, and value ranges to isolate the ball from everything else. The main function cycles through the channels of an HSV image (hue, saturation, and value), allowing the user to try different bounds for each channel in turn, and displaying the result. In the end, it returns the new bounds, as well as the center position and radius of the final circle that was discovered, marking the location of the ball.</p>
<p>The <code>applyBounds</code> function does most of the work of processing and displaying the images. It does these steps:</p>
<ul>
<li>It uses <code>inRange</code> to make a threshold image based on the current values for the lower and upper bounds</li>
<li>It calls <code>findContours</code> to find all the closed curves in the threshold image</li>
<li>It searches the contours to find the largest contour that was found</li>
<li>It draws that contour on a copy of the original image</li>
<li>It finds the smallest enclosing circle for the contourl and draws that as well</li>
<li>It displays some text on the image to show the user what is happening</li>
<li>Finally, it returns the image, along with the center position and radius of the circle it has drawn</li>
</ul>
<p><strong>Your task</strong> will be to implement the three helper functions that help the user to adjust the hue thresholds, the saturation thresholds, and the value thresholds. I will provide you with pseudocode for all three functions just below, and a few sample calls to show what results the user should be able to construct.</p>
<p><strong>Hints:</strong></p>
<ul>
<li>Display all images here in a single window called <code>"Ball Finder"</code> for simplicity</li>
<li>Remember that you can’t modify tuples, you will need to rebuild them each time you make a change</li>
<li>There is a cryptic but clever programming “hack” for times when you need a value to stay above (or below) a certain value. Suppose I am adding one to a variable <code>x</code>, and I want to make sure that <code>x</code> never goes over 100. I could write the following statement by itself to do this:</li>
</ul>
<div id="35b878ea" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1"></a>x <span class="op">=</span> <span class="bu">min</span>(<span class="dv">100</span>, x <span class="op">+</span> <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="pseudocode-for-adjusthue" class="level2">
<h2 class="anchored" data-anchor-id="pseudocode-for-adjusthue">Pseudocode for <code>adjustHue</code></h2>
<p>The <code>adjustHue</code> function takes in the image (in BGR format) and two tuples (the lower and upper bounds for <code>inrange</code>). It should loop until the user presses the space bar to go on. Each time through the loop it displays the current contour found, and lets the user alter the range of hues.</p>
<p>We know that <code>inRange</code> works best with a narrow range of hue values. So we will represent a single hue, the middle of a range of 20 hue values, and we will calculate the lower and upper bound from that middle hue. The user will change the hue by hitting either the w or the s key: w will increase the hue value by 5, s will reduce it by 5.</p>
<p>Here is the detailed pseudocode:</p>
<pre><code>Algorithm adjustHue(image, lowerBounds, upperBounds)
1. Let currHue be the average of the input lower-bound hue and the upper-bound hue
2. Loop until the user indicates to quit
3.     Call applyBounds and pass it image, lowerBounds, upperBounds, and a string "Adjusting hue"
4.     Save the result of the call in a variable, newIm
5.     Display newIm with imshow
6.     Use waitKey to pause and to get a key value from the user
7.     If the user hit the space key, then break out of the loop
8.     If the user hit the 'w' key then:
9.          Add 5 to currHue, but make sure it doesn't go over 170
10.         Create a new set of lower bounds, updating its low hue value to currHue - 10
11.         Create a new set of upper bounds, update its high hue value to currHue + 10
12.    If the user hit the 's' key then:
13.         Subtract 5 from currHue, but make sure it doesn't go below 10
14.         Create a new set of lower bounds, updating its low hue value to currHue - 10
15.         Create a new set of upper bounds, update its high hue value to currHue + 10
16. After the loop ends, return the final lower bounds and upper bounds, and the center point and radius of the circle
from applyBounds</code></pre>
</section>
<section id="pseudocode-for-adjustsat" class="level2">
<h2 class="anchored" data-anchor-id="pseudocode-for-adjustsat">Pseudocode for <code>adjustSat</code></h2>
<p>This function will be very similar to the previous one, but now we have to change the lower saturation bound separately from the upper saturation bound. So we will use four key presses (w, s, e, and d) rather than just the two we needed for <code>adjustHue</code>.</p>
<p>The <code>adjustSat</code> function takes in the image (in BGR format) and two tuples (the lower and upper bounds for <code>inrange</code>). It should loop until the user presses the space bar to go on. Each time through the loop it displays the current contour found, and lets the user alter the lower or upper saturation bound.</p>
<p>Here is the detailed pseudocode:</p>
<pre><code>Algorithm adjustSat(image, lowerBounds, upperBounds)
1. Let lowSat be the saturation lower bound from lowerBounds
2. Let uppSat be the saturation upper bound from upperBounds
3. Loop until the user indicates to quit
4.     Call applyBounds and pass it image, lowerBounds, upperBounds, and a string "Adjusting sat"
5.     Save the result of the call in a variable, newIm
6.     Display newIm with imshow
7.     Use waitKey to pause and to get a key value from the user
8.     If the user hit the space key, then break out of the loop
9.     If the user hit the 'w' key then:
10.         Add 5 to lowSat, but make sure it doesn't go over uppSat
11.         Create a new set of lower bounds, updating its low saturation value to lowSat
13.    If the user hit the 's' key then:
14.         Subtract 5 from lowSat, but make sure it doesn't go below 0
15.         Create a new set of lower bounds, updating its low saturation value to lowSat
16.    If the user hit the 'e' key then:
17.         Add 5 to uppSat, but make sure it doesn't go over 255
18.         Create a new set of upper bounds, updating its upper saturation value to uppSat
19.    If the user hit the 'd' key then:
20          Subtract 5 from uppSat, but make sure it doesn't go below lowSat
21.         Create a new set of upper bounds, updating its upper saturation value to uppSat
22. After the loop ends, return the final lower bounds and upper bounds, and the center point and radius of the circle
from applyBounds</code></pre>
</section>
<section id="pseudocode-for-adjustval" class="level2">
<h2 class="anchored" data-anchor-id="pseudocode-for-adjustval">Pseudocode for <code>adjustVal</code></h2>
<p>The <code>adjustVal</code> function will be almost identical to the <code>adjustSat</code> one, except that we look at the third entries in the bounds tuples, rather than the second ones. Because of that, I won’t include the pseudocode over again.</p>
</section>
<section id="testing-your-program" class="level2">
<h2 class="anchored" data-anchor-id="testing-your-program">Testing your program</h2>
<p>Once you have written one of these functions, be sure to test it. Be sure that you test multiple factors:</p>
<ul>
<li>Make sure that the limits on the updated values hold: that the hue values never go below 0 or above 180, that the <code>lowSat</code> value can’t go below 0, or above <code>uppSat</code>, etc.</li>
<li>Make sure that the lower and upper bounds change correctly as you type the w, s, e, or d keys.</li>
<li>Watch that changes to the bounds do (eventually) bring changes to the displayed contours and circles</li>
<li>Examine the visual results carefully and experiment until you can isolate the ball in each of the pictures.</li>
</ul>
<p>Below is a series of sample calls to this function, duplicated in the <code>hw3Checker.py</code> program. In <a href="#fig-q3results" class="quarto-xref">Figure&nbsp;4</a> you can see the kind of results you should be able to reach by adjusting hue, saturation, and value bounds.</p>
<div id="e8cc7aa2" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a>pic1 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/Blue1BG1Mid.jpg"</span>)</span>
<span id="cb5-2"><a href="#cb5-2"></a>pic2 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/Blue1BG3.jpg"</span>)</span>
<span id="cb5-3"><a href="#cb5-3"></a>pic3 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/Green1BG1Mid.jpg"</span>)</span>
<span id="cb5-4"><a href="#cb5-4"></a>pic4 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/Green1BG3.jpg"</span>)</span>
<span id="cb5-5"><a href="#cb5-5"></a>pic5 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/OrangeBG1Near.jpg"</span>)</span>
<span id="cb5-6"><a href="#cb5-6"></a>pic6 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/PinkBG1Mid.jpg"</span>)</span>
<span id="cb5-7"><a href="#cb5-7"></a>pic7 <span class="op">=</span> cv2.imread(<span class="st">"SampleImage/BallFinding/YellowBG1Mid.jpg"</span>)</span>
<span id="cb5-8"><a href="#cb5-8"></a></span>
<span id="cb5-9"><a href="#cb5-9"></a><span class="cf">for</span> pic <span class="kw">in</span> [pic1, pic2, pic3, pic4, pic5, pic6, pic7]:</span>
<span id="cb5-10"><a href="#cb5-10"></a>    im, lb, ub, cnt, rad <span class="op">=</span> hw3.findBall(pic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-q3results" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-q3results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/blue1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Good result for Blue1BG1Mid.jpg"><img src="HW3-Images/blue1.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>Blue1BG1Mid.jpg</code></figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/blue2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Good result for Blue1BG3.jpg"><img src="HW3-Images/blue2.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>Blue1BG3.jpg</code></figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/green1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Good result for Green1BG1Mid.jpg"><img src="HW3-Images/green1.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>Green1BG1Mid.jpg</code></figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/green2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Good result for Green1BG3.jpg"><img src="HW3-Images/green2.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>Green1BG3.jpg</code></figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/orange1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Good result for OrangeBG1Near.jpg"><img src="HW3-Images/orange1.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>OrangeBG1Near.jpg</code></figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/pink1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Good result for PinkBG1Mid.jpg"><img src="HW3-Images/pink1.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>PinkBG1Mid.jpg</code></figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="HW3-Images/yellow1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Good result for YellowBG1Mid.jpg"><img src="HW3-Images/yellow1.png" class="img-fluid figure-img"></a></p>
<figcaption>Good result for <code>YellowBG1Mid.jpg</code></figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-q3results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Seven examples, showing good, perhaps best possible, results from user tinkering with bounds
</figcaption>
</figure>
</div>
</section>
<section id="specifications-for-question-3" class="level2">
<h2 class="anchored" data-anchor-id="specifications-for-question-3">Specifications for Question 3</h2>
<p><strong>Base specifications:</strong></p>
<ul>
<li>Defines all three functions with the correct headers: names and inputs for each</li>
<li>The <code>adjustHue</code> function:
<ul>
<li>Correctly computes the starting value for <code>currHue</code> as described in the pseudocode</li>
<li>Uses a <code>while</code> loop correctly, quitting when the user presses the space key</li>
<li>Correctly calls <code>applyBounds</code> and displays the result</li>
<li>Updates <code>currHue</code> correctly when the user presses the w or s key</li>
<li>Correctly limits <code>currHue</code> to be between 10 and 170</li>
<li>Returns the updated lower and upper bounds, and the position and size of the circle</li>
</ul></li>
<li>The <code>adjustSat</code> function:
<ul>
<li>Uses a <code>while</code> loop correctly, quitting when the user presses the space key</li>
<li>Correctly calls <code>applyBounds</code> and displays the result</li>
<li>Changes the lower saturation bound correctly in response to user pressing w or s</li>
<li>Changes the upper saturation bound correctly in response to user pressing e or d</li>
<li>Correctly limits the lower and upper saturation bounds so that the lower bound does not go below zero, or above the upper bound, and the upper bound does not go above 255 or below the lower bound</li>
<li>Returns the updated lower and upper bounds, and the position and size of the circle</li>
</ul></li>
<li>The <code>adjustVal</code> function:
<ul>
<li>Uses a <code>while</code> loop correctly, quitting when the user presses the space key</li>
<li>Correctly calls <code>applyBounds</code> and displays the result</li>
<li>Changes the lower value bound correctly in response to user pressing w or s</li>
<li>Changes the upper value bound correctly in response to user pressing e or d</li>
<li>Correctly limits the lower and upper value bounds so that the lower bound does not go below zero, or above the upper bound, and the upper bound does not go above 255 or below the lower bound</li>
<li>Returns the updated lower and upper bounds, and the position and size of the circle</li>
</ul></li>
</ul>
<p><strong>Extended specifications:</strong></p>
<ul>
<li>Code includes a triple-quoted <em>docstring</em> that describes the function’s input, purpose, and results</li>
<li>Student name is at the top of the file</li>
<li>Any completed TODO comments have been removed</li>
<li>File format has appropriate style:
<ul>
<li><code>import</code> statements at the top</li>
<li>then function definitions with no script elements</li>
<li>then the main script, all insidde the <code>if __name__ == '__main__':</code> statement</li>
</ul></li>
</ul>
<p><strong>Ratings:</strong></p>
<ul>
<li>To receive a gold rating, complete at least 3 general specifications, plus at least 5 specifications for each function</li>
<li>To receive a silver rating, complete at least 2 general specifications, plus at least 4 specifications for each function</li>
<li>To receive a bronze rating, complete at least 2 general specifications, plus at least 3 specifications for each function</li>
</ul>
</section>
</section>
<section id="question-4-writing-pseudocode" class="level1">
<h1>Question 4: Writing pseudocode</h1>
<p>Suppose we want to use morphological filters on a video feed to make the video look a little bit glitchy. To do this, we will apply morphological filters to each frame of the video. We will keep a fixed neighborhood size of (9, 9), and a fixed neighborhood shape: an ellipse. However, every 5 to 15 frames, we will change the morphological filter we are going to use, choosing a new one at random from among: erosion, dilation, opening, blackhat, and gradient.</p>
<p>Write pseudocode that describes how to implement this task. Be detailed, but don’t write Python code (see the pseudocode I provided for the previous questions for the right level). Your algorithm should take in the source for the video (if you implemented this, it would be 0 for the webcam or a string if reading from a video file).</p>
<p>Here are some things to think about as you design a solution:</p>
<ul>
<li>The heart of this program is the typical video pattern (using <code>VideoCapture</code>, reading, processing, and displaying frames)</li>
<li>To randomly select an operation, you could put the operation codes in a list and choose random elements from it</li>
<li>To vary how long between changes, think about having a countdown timer variable that is set to a random starting value each time there is a change</li>
</ul>
<section id="specifications-for-question-4" class="level2">
<h2 class="anchored" data-anchor-id="specifications-for-question-4">Specifications for Question 4</h2>
<p><strong>Base specifications:</strong></p>
<ul>
<li>Pseudocode is readable: what each line does is clearly stated</li>
<li>Pseudocode correctly describes the overall process of working with and processing frames from a video</li>
<li>Pseudocode correctly describes a method for randomly selecting a morphological operation</li>
<li>Pseudocode correctly describe a method for randomly varying the time between changes from 5 to 15 frames</li>
<li>Pseudocode displays the morphed image</li>
</ul>
<p><strong>Extended specifications:</strong></p>
<ul>
<li>Student name is at the top of the file</li>
<li>Any completed TODO comments have been removed</li>
<li>File format has appropriate style:
<ul>
<li><code>import</code> statements at the top</li>
<li>then function definitions with no script elements</li>
<li>then the main script, all inside the <code>if __name__ == '__main__':</code> statement</li>
</ul></li>
</ul>
<p><strong>Ratings:</strong></p>
<ul>
<li>To receive a gold rating, fully complete 5 specifications, at least 4 base, and partially complete at least 1 more</li>
<li>To receive a silver rating, fully complete at least 4 specifications, at least 3 base, and partially complete at least 1 more</li>
<li>To receive a bronze rating, fully complete at least 3 specifications, at lesat 2 base, partially complete at least 1 more</li>
</ul>
</section>
</section>
<section id="question-5-augmenting-an-existing-program" class="level1">
<h1>Question 5: Augmenting an existing program</h1>
<p>In the <code>hw3Code.py</code> file, you will find a version of the Camshift program. In this case, you pass it a reference picture, and it tries to find and track an object that matches the color in the reference picture.</p>
<p>Try out this program using any brightly-colored objects you have (you can borrow some of the colorful balls or other objects from my CV bag if you like.) I provided three reference images, to blue, green, or pink balls I have in my collection. But even if you use those, you might need to make your own reference images.</p>
<p>Look back at the readings or in-class activity for more details about how to make a reference image.</p>
<p><strong>Your task:</strong> Your task is to extend this program so that it can track two differently-colored objects at the same time. You will need to do the following:</p>
<ul>
<li>Change the function header so that it takes in two reference pictures</li>
<li>Set up two separate histograms, one for each reference picture</li>
<li>Set up two separate track windows</li>
<li>Process the frame twice, once for each histogram/track window</li>
<li>Draw ellipses for both objects on the frame before displaying it (be sure to draw them in two different colors)</li>
</ul>
<p><strong>A challenge for you:</strong> Suppose you wanted to track two objects of the <em>same</em> color. Try that once you get your solution working: what happens? Can you figure out a way to solve the problem?</p>
<section id="specifications-for-question-5" class="level2">
<h2 class="anchored" data-anchor-id="specifications-for-question-5">Specifications for Question 5</h2>
<p><strong>Base specifications:</strong></p>
<ul>
<li>Function takes two inputs, both reference images, with meaningful variable names</li>
<li>Function correctly sets up two histograms</li>
<li>Function correctly sets up two track windows and updates each of them at the same points in the same way</li>
<li>Function processes the original frame twice: once for each histogram/track window pairing</li>
<li>Function records both new track boxes and both new track windows, and draws ellipses correctly to show the track boxes</li>
<li>Overall processing of video is handled correctly</li>
</ul>
<p><strong>Extended specifications:</strong></p>
<ul>
<li>Docstring is updated to reflect the function’s new operations</li>
<li>Student name is at the top of the file</li>
<li>Any completed TODO comments have been removed</li>
<li>File format has appropriate style:
<ul>
<li><code>import</code> statements at the top</li>
<li>then function definitions with no script elements</li>
<li>then the main script, all insidde the <code>if __name__ == '__main__':</code> statement</li>
</ul></li>
</ul>
<p><strong>Ratings:</strong></p>
<ul>
<li>To receive a gold rating, complete at least 8 specifications in all, at least 5 of them base specifications.</li>
<li>To receive a silver rating, complete at least 7 specifications in all, at least 4 of them base.</li>
<li>To receive a bronze rating, complete at least 5 total specifications, at least 2 of them base.</li>
</ul>
</section>
</section>
<section id="question-6-writing-a-program-of-your-own-design" class="level1">
<h1>Question 6: Writing a program of your own design</h1>
<p>For this question, I’m asking you to unleash your creativity, and use the image processing and image transformation tools we have learned to modify a video feed to display your chosen “vibe”.</p>
<ul>
<li>Add spooky effects</li>
<li>Add happy, bouncy, Kpop effects</li>
<li>Add gentle, relaxing effects</li>
</ul>
<p>It’s your choice (keep it all family-friendly).</p>
<p>Here are the techniques you could apply here:</p>
<ul>
<li>Brightening/darkening with image arithmetic</li>
<li>Cropping or resizing other images to substitute randomly or periodically for the video feed
<ul>
<li>Flashing other images, almost like subliminal messages</li>
<li>Or blending a beautiful image with the camera feed for a soothing effect</li>
</ul></li>
<li>Using masks or threshold images in themselves or to let you add or substitute parts of other images over the video feed
<ul>
<li>You could add small pictures to the video feed background</li>
<li>You could change every pixel matching a certain color range to another color</li>
</ul></li>
<li>Using geometric transformations to make the camera view move, rotate, skew, etc.</li>
<li>Using image filters to alter the look of the video feed (blurring, morphing, edge detection)</li>
<li>Using motion detection to get a weird effect, or to highlight places in an image where motion is happening
<ul>
<li>You could brighten/darkent parts that have movement, or tint them</li>
</ul></li>
</ul>
<p><strong>Choose at least four different kinds of transformations from the list below</strong> and apply them across the frames of the video. You can apply them to all of a frame, or just to part of the frame. Ideally the transformation will not be statc: it should change in amount or intensity over time, or only be applied periodically, etc. Here is the list:</p>
<ol type="1">
<li>Brighten/darken part or all of an image</li>
<li>Tint part or all of an image</li>
<li>Blend part or all of an image</li>
<li>Substitute another image for part or all of an image</li>
<li>Apply a mask to part or all of an image</li>
<li>Apply grayscale or color thresholding to part or all of an image</li>
<li>Apply translation to part or all of an image</li>
<li>Apply rotation to part or all of an image</li>
<li>Apply general affine warping (or perspective warping) to part or all of an image</li>
<li>Apply blurring to part or all of an image</li>
<li>Apply one or more morphological filters to part or all of an image</li>
<li>Apply edge detection (Sobel or Canny) to part or all of an image</li>
<li>Apply simple motion detection to part or all of an image</li>
</ol>
<p>Incorporate your effects into a function called <code>videoVibe</code> that applies your transformations to a video feed. Like earlier examples, <code>videoVibe</code> should have one parameter input, either a webcam number or a string path to a stored video file (unmodified).</p>
<p>Feel free to use helper functions where it makes sense.</p>
<p>Use good style, and comment your code!</p>
<p>In the code file, include a triple-quoted string above your <code>videoVibe</code> function where you write a paragraph or two about what vibe you were going for, and how you feel the transformations you did contribute to that vibe.</p>
<p><strong>A note about testing:</strong> The <code>check_videoVibe</code> function in <code>hw3Checker.py</code> uses several stored videos from our <code>SampleVideos</code> folder. These videos are too large to be stored in Github. Just copy them to the <code>SampleImages</code> folder before testing with them.</p>
<section id="specifications-for-question-6" class="level2">
<h2 class="anchored" data-anchor-id="specifications-for-question-6">Specifications for Question 6</h2>
<p><strong>Base specifications:</strong></p>
<ul>
<li>Solution defines a function called <code>videoVibe</code> with the right input parameter</li>
<li>This function and any helpers all have clear descriptive docstring comments, and include hash-mark comments at key points within their definitions</li>
<li>This program incorporates at least four transformations from the list above</li>
<li>The transformations are not static, but change over time</li>
<li>The program is effective in generating the effect, or vibe, the programmer says they were looking for</li>
</ul>
<p><strong>Extended specifications:</strong></p>
<ul>
<li>Some transformations include randomness to make the effects less predictable</li>
<li>Student name is at the top of the file</li>
<li>Any completed TODO comments have been removed</li>
<li>File format has appropriate style:
<ul>
<li><code>import</code> statements at the top</li>
<li>then function definitions with no script elements</li>
<li>then the main script, all inside the <code>if __name__ == '__main__':</code> statement</li>
</ul></li>
</ul>
<p><strong>Ratings:</strong></p>
<ul>
<li>To receive a gold rating, complete at least 6 specifications in all, at least 5 of them base.</li>
<li>To receive a silver rating, complete at least 5 specifications in all, at least 4 of them base.</li>
<li>To receive a bronze rating, complete at least 4 total specifications, at least 3 of them base.</li>
</ul>
</section>
</section>
<section id="what-to-hand-in" class="level1">
<h1>What to hand in</h1>
<p>You will hand in your work using <strong>commit</strong> and <strong>push</strong> to copy the files to Github (you should commit and push after every work session, not just at the end).</p>
<p>You should make sure these files are added by git to the files it is tracking:</p>
<ul>
<li><code>hw3Code.py</code> (all your work goes here)</li>
<li><code>hw3Checker.py</code></li>
<li>The selected images/videos in the <code>SampleImages</code> folder</li>
<li>Any other images you used</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>